### ISSUE TITLE
But i have new bug

### ISSUE THREAD

**Issue by Kozlov-V** [titan098/rackspace_cloud_files#3]
Sorry, for my persistence)))
But i have new bug, when i create new app.
When i start my app i have this error:

{"init terminating in do_boot",{{badmatch,
{error,{already_started,crypto}}},[{cdn,start,0,[{file,"src/cdn.erl"},{line,12}]
},{init,start_it,1,[]},{init,start_em,1,[]}]}}

listing src/cdn.erl
%% Feel free to use, reuse and abuse the code in this file.

``` -module(cdn).
-export([start/0]).
start() ->
    ok = application:start(rackspace_cloud_files),
       ok = application:start(crypto),
    ok = application:start(ranch),
    ok = application:start(cowboy),
    ok = application:start(cdn).
```

When i replace start(crypto) on a first, app hase start, but when i was exec
rackspace_cloud_files:tempurl_create_url(get,"testCont", Name, 600, "123456")
i have this error

```
==ERROR REPORT==== 26-Mar-2013::15:49:16 ===
** Generic server rackspace_cloud_files_srv terminating
** Last message in was {execute_function,tempurl_create_url,
                           [get,"test",
                            "80a543449156ce35c010777514987c04-v.flv",600,
                            "123456"]}
** When Server state == {state,"https://auth.api.rackspacecloud.com/v1.0",
                               "myname","1e6647c9825a59eEcualKey",
                               "8693f872-7448-4841-b394-295b9584b92e",
                               1364298491,
                               "https://storage101.dfw1.clouddrive.com/v1/MossoC
loudFS_b9097169-5901-49ca-ab6d-b2e0a444c4d0",
                               "https://cdn1.clouddrive.com/v1/MossoCloudFS_b909
7169-5901-49ca-ab6d-b2e0a444c4d0"}
** Reason for termination ==
** {'function not exported',
       [{crypto,hmac,
            [sha,"123456",
             "GET\n1364299156\n/v1/MossoCloudFS_b9097169-5901-49ca-ab6d-b2e0a444
c4d0/test/80a543449156ce35c010777514987c04-v.flv"],
            []},
        {rackspace_cloud_files_api,tempurl_create_url,6,
            [{file,"src/rackspace_cloud_files_api.erl"},{line,560}]},
        {rackspace_cloud_files_srv,handle_call,3,
            [{file,"src/rackspace_cloud_files_srv.erl"},{line,101}]},
        {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,588}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}
** exception exit: {{undef,
                        [{crypto,hmac,
                             [sha,"123456",
                              "GET\n1364299156\n/v1/MossoCloudFS_b9097169-5901-4
9ca-ab6d-b2e0a444c4d0/test/80a543449156ce35c010777514987c04-v.flv"],
                             []},
                         {rackspace_cloud_files_api,tempurl_create_url,6,
                             [{file,"src/rackspace_cloud_files_api.erl"},
                              {line,560}]},
                         {rackspace_cloud_files_srv,handle_call,3,
                             [{file,"src/rackspace_cloud_files_srv.erl"},
                              {line,101}]},
                         {gen_server,handle_msg,5,
                             [{file,"gen_server.erl"},{line,588}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,227}]}]},
                    {gen_server,call,
                        [rackspace_cloud_files_srv,
                         {execute_function,tempurl_create_url,
                             [get,"test",
                              "80a543449156ce35c010777514987c04-v.flv",600,
                              "123456"]},
                         60000]}}
     in function  gen_server:call/3 (gen_server.erl, line 188)
```

i was testing this whithout cowboy app, only standalone rackspace_cloud_files and i have result too

**Comment by Kozlov-V** [comment]
its no resolve problem
i have bug too(((

**Comment by titan098** [comment]
Hello,

With reference to the "function not exported" message when generating a tempurl, I was originally using the `crypto:hmac/3` function, however this seems to have only been included in later versions of the `crypto` module. I switched it for the `crypto:sha_mac/2` function and tested the generation of tempurl's on R15B01 (crypto module version 2.1) and R16B (crypto module version 2.3), so this should work now. The change is on the develop branch, if it works successfully I will merge it with the master branch.

With reference to `ok = application:start(crypto)`, the `ibrowse` application (which is started when you call `application:start(rackspace_cloud_files)`) does start `crypto` itself, so there is no real need for you to start it. 

However, as the application has already been started when you then try to execute `application:start(crypto)` the term `{error, already_started}` is returned which won't match with `ok` causing the error you are experiencing.  The simplest fix is to just call `application:start(crypto)` which will fail silently if the application has already been started.

Hope this helps.

**Comment by titan098** [comment]
Hello,

What version of Erlang/OTP are you running? could you also check the exports for the crypto module on your system.

For R15B01 (Ubuntu 12.10) my system reports:

``` erlang
1> lists:keyfind(sha_mac, 1, crypto:module_info(exports)). 
{sha_mac,2}
2> lists:keyfind(hmac, 1, crypto:module_info(exports)).   
false
```

and for R16B (Mac OS X) my system reports:

``` erlang
2> lists:keyfind(sha_mac, 1, crypto:module_info(exports)). 
{sha_mac,2}
3> lists:keyfind(hmac, 1, crypto:module_info(exports)). 
{hmac,3}
```

**Comment by Kozlov-V** [comment]
Hello!
Sorry for the late reply.
You gave a lot of food for thought, and tests.
During the tests revealed the following:
1) `crypto:hmac/3` only works on OTP_R16B (here's my fault, I did not see any difference OTP versions on the host).
2) `crypto:sha_mac/2` runs on OTP_R15B02 and OTP_R16B

My OS - Debian 6, ms windows 7 pro

But I decided to choose to `crypto:hmac/3` and OTP_R16B
It nice work!!!
